# Generated by Django 5.1.6 on 2025-03-02 13:47

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_registration_date', models.DateTimeField(auto_now_add=True)),
                ('user_code', models.CharField(default=home.models.generate_random_code, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users', to_field='user_code')),
            ],
        ),
    ]
