# Generated by Django 5.1.3 on 2025-03-01 20:03

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_password', models.CharField(max_length=255)),
                ('user_registration_date', models.DateTimeField(auto_now_add=True)),
                ('user_code', models.CharField(default=home.models.generate_random_code, max_length=20, unique=True)),
            ],
        ),
    ]
