# Generated by Django 5.1.6 on 2025-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap', models.CharField(max_length=200)),
                ('yazar', models.CharField(max_length=100)),
                ('sayfa', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_code',
        ),
    ]
