# Generated by Django 5.1.3 on 2025-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
